name: tradaul
description: Lua implementation in Dart
version: 0.7.0
repository: https://github.com/szktty/tradaul

environment:
  sdk: ^3.0.5

dependencies:
  args: ^2.4.2
  clock: ^1.1.1
  collection: ^1.18.0
  file: ^7.0.0
  fixnum: ^1.1.0
  freezed_annotation: ^2.2.0
  logging: ^1.2.0
  meta: ^1.10.0
  path: ^1.8.3
  petitparser: ^5.4.0
  result_dart: ^1.1.0
  sprintf: ^7.0.0
  string_scanner: ^1.2.0
  very_good_analysis: ^5.0.0+1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  freezed: ^2.3.5
  build_runner: ^2.4.5
